In [11]:
# Q1
import numpy as np
list_=['1','2','3','4','5']
array_list=np.array(object = list_)
print(array_list)
print(type(array_list))
print(type(list_))

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>
<class 'list'>


In [13]:
#Q2
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [18]:
#Q3
array_list=np.array(object=list_, dtype=int)
print(list_)
for element in list_:
  print(type((element)))

print(array_list)
for element in array_list:
  print(type(element))
''' The element in list are string now and the element inn aaray_list
converting the element from strings to integers
'''

['1', '2', '3', '4', '5']
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
[1 2 3 4 5]
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


' The element in list are string now and the element inn aaray_list converting\nthe element from strings to integers\n'

In [20]:
#Q4
import numpy as nnp
num_list=[[1,2,3],[4,5,6]]
num_array=np.array(object=num_list)
shape=num_array.shape
size=num_array.size
print(size)
print(shape)

6
(2, 3)


In [22]:
#Q5
import numpy as np
zero_array=np.zeros((3,3))
print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
#Q6
zeros_array=np.zeros((5,5))
print(zeros_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
